### ISSUE TITLE
请问你的教材是哪本，能否发张图片。

### ISSUE THREAD

**Issue by CChuancey** [wwyqianqian/ccnu-c-plus-plus#7]
不方便的话，能否说下出版社和作者。谢谢了

**Comment by wwyqianqian** [comment]
当时上课老师没有指定教材，不过有其他同学在 Y Daniel Liang 写的机械工业出版社 2015.1 出版的《C++ 程序设计》这本书中，找到了相似的内容。ISBN: 9787111485148。
